plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

title: [CNCTorture]
description: [Test files for CNC/CAM Development, Testing, and Bug Reporting]
theme: jekyll-theme-slate
show_downloads: ["true"]
google_analytics: [UA-16164137-3]
